# Site settings
remote_theme: "Jekyll Theme - BlogFolio"
name: Jeremiah Volkmer 
email: jvolkmer32@gmail.com 
url: jeremiahvolkmer.github.io 
description: "A blog and a portfolio"
author: "Jeremiah"
title: "Bluedog Blog"
permalink: pretty
baseurl: /

# social
github:
  username: jeremiahvolkmer 

twitter:
  username: username
